use rand::Rng;

pub const ATTRIBUTES: &[&str] = &[
    "admiring", "agile", "alert", "bold", "brave", "bright", "calm", "careful", "clever", "cool",
    "daring", "dazzling", "eager", "earnest", "elegant", "epic", "fair", "fast", "fierce", "fine",
    "fluent", "fond", "free", "fresh", "gentle", "gifted", "glad", "graceful", "grand", "happy",
    "hardy", "keen", "kind", "lively", "loyal", "lucky", "merry", "mighty", "noble", "patient",
    "playful", "polite", "proud", "pure", "quick", "quiet", "radiant", "serene", "sharp", "sleek",
    "smart", "speedy", "strong", "sunny", "sure", "swift", "tender", "valiant", "warm", "witty",
    "zeal",
];

pub const COLOURS: &[&str] = &[
    "amber",
    "aqua",
    "auburn",
    "azure",
    "beige",
    "black",
    "blue",
    "blush",
    "brown",
    "bronze",
    "cherry",
    "cobalt",
    "coral",
    "cream",
    "crimson",
    "cyan",
    "ebony",
    "fawn",
    "flax",
    "fuchsia",
    "gold",
    "gray",
    "green",
    "indigo",
    "ivory",
    "jade",
    "khaki",
    "lavender",
    "lemon",
    "lime",
    "magenta",
    "maroon",
    "mauve",
    "mint",
    "navy",
    "nude",
    "ochre",
    "olive",
    "orange",
    "peach",
    "pink",
    "plum",
    "purple",
    "red",
    "rose",
    "ruby",
    "russet",
    "sage",
    "scarlet",
    "silver",
    "tan",
    "teal",
    "violet",
    "white",
    "yellow",
    "ultramarine",
    "lightblue",
    "lightgreen",
    "lightpink",
];

pub const FLOWERS: &[&str] = &[
    "aster",
    "azalea",
    "bluebells",
    "blossom",
    "camellia",
    "carnation",
    "clover",
    "cosmos",
    "cactus",
    "dahlia",
    "daisy",
    "fern",
    "flox",
    "freesia",
    "gardenia",
    "heather",
    "hibiscus",
    "hollyhock",
    "hyacinth",
    "iris",
    "ivy",
    "jasmine",
    "lantana",
    "larkspur",
    "lilac",
    "lily",
    "lobelia",
    "lotus",
    "lupin",
    "magnolia",
    "mallow",
    "marigold",
    "mint",
    "myrtle",
    "orchid",
    "pansy",
    "peony",
    "petunia",
    "poppy",
    "primrose",
    "rose",
    "snapdragon",
    "sunflower",
    "thyme",
    "tulip",
    "verbena",
    "violet",
    "wisteria",
    "yarrow",
    "zinnia",
];

pub fn generate_username<R: Rng>(rng: &mut R) -> String {
    let attr = ATTRIBUTES[rng.gen_range(0..ATTRIBUTES.len())];
    let colour = COLOURS[rng.gen_range(0..COLOURS.len())];
    let flower = FLOWERS[rng.gen_range(0..FLOWERS.len())];
    format!("{}-{}-{}", attr, colour, flower)
}
