//! Live LLM-backed adaptation service.
//!
//! Calls the configured Ollama model with the task's `command_template` and
//! the player's profile metadata, parses the JSON-array response into concrete
//! `tests` rows, then normalizes commands to plain shell text before
//! writing to the DB.
use crate::adaptation::command_policy::split_when_safe;
use crate::adaptation::metrics::AdaptationMetrics;
use crate::adaptation::service::{AdaptationError, AdaptationRequest, AdaptationService};
use crate::llm::{LlmError, LlmServiceHandle};
use arena_core::entities::tests as entity_tests;
use async_trait::async_trait;
use chrono::Utc;
use sea_orm::{
    ActiveModelTrait, ColumnTrait, DatabaseConnection, EntityTrait, PaginatorTrait, QueryFilter,
    Set, TransactionTrait,
};
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::Semaphore;
use uuid::Uuid;

pub const LLM_TIMEOUT_SECS_DEFAULT: u64 = 60;

/// One test case generated by the LLM from the task's `command_template`.
#[derive(Debug, serde::Deserialize)]
struct AdaptedTest {
    prompt: String,
    command: String,
    expected_answer: String,
    /// Optional minijinja expression evaluated against the `result` variable
    /// (trimmed stdout).  Provided by the LLM when exact equality is insufficient
    /// (e.g. `result != ""`, `"PASS" in result`).  If absent the concrete
    /// `expected_answer` string is used for comparison.
    #[serde(default)]
    answer_template: Option<String>,
}

fn expand_atomic_tests(tests: Vec<AdaptedTest>) -> Result<Vec<AdaptedTest>, String> {
    let mut expanded = Vec::new();

    for test in tests {
        let parts = split_when_safe(&test.command).map_err(|e| e.as_code().to_string())?;
        if parts.len() == 1 {
            expanded.push(AdaptedTest {
                prompt: test.prompt,
                command: parts[0].clone(),
                expected_answer: test.expected_answer,
                answer_template: test.answer_template,
            });
            continue;
        }

        for (idx, part) in parts.into_iter().enumerate() {
            expanded.push(AdaptedTest {
                prompt: format!("{} (check {})", test.prompt, idx + 1),
                command: part,
                expected_answer: test.expected_answer.clone(),
                answer_template: test.answer_template.clone(),
            });
        }
    }

    if expanded.is_empty() {
        return Err("empty_test_list".to_string());
    }

    Ok(expanded)
}

pub struct LiveAdaptationService {
    db: DatabaseConnection,
    llm: LlmServiceHandle,
    llm_timeout_secs: u64,
    semaphore: Arc<Semaphore>,
    metrics: Arc<AdaptationMetrics>,
    settings_encryption: Arc<arena_core::settings_encryption::SettingsEncryption>,
}

impl LiveAdaptationService {
    pub fn from_env(
        db: DatabaseConnection,
        llm: LlmServiceHandle,
        semaphore: Arc<Semaphore>,
        metrics: Arc<AdaptationMetrics>,
        settings_encryption: Arc<arena_core::settings_encryption::SettingsEncryption>,
    ) -> Self {
        Self {
            db,
            llm,
            llm_timeout_secs: LLM_TIMEOUT_SECS_DEFAULT,
            semaphore,
            metrics,
            settings_encryption,
        }
    }
}

#[async_trait]
impl AdaptationService for LiveAdaptationService {
    async fn adapt(&self, req: AdaptationRequest) -> Result<(), AdaptationError> {
        // Idempotency: if rows already exist for (session_id, task_id),
        // adaptation already ran — skip the LLM call and use existing rows.
        let existing: u64 = entity_tests::Entity::find()
            .filter(entity_tests::Column::SessionId.eq(req.session_id))
            .filter(entity_tests::Column::TaskId.eq(req.task_id))
            .count(&self.db)
            .await
            .map_err(|e| AdaptationError::DbError(e.to_string()))?;
        if existing > 0 {
            return Ok(());
        }

        // Operation-scoped model: `llm_op_adaptation` assignment → default
        // assignment (empty-model sentinel when nothing is configured).
        let cfg = crate::llm::resolve_model_for_operation(
            &self.db,
            &self.settings_encryption,
            "adaptation",
        )
        .await;

        let system_prompt = build_system_prompt(&req.player_metadata);

        let user_prompt = format!(
            "Schema version: {}\n\nProject name: {}\n\nProject description:\n{}\n\nTask title: {}\n\nTask description:\n{}\n\nTask tags: {}\n\nTest template:\n{}\n\nPlayer metadata:\n{}",
            req.schema_version,
            req.project_name,
            req.project_description,
            req.task_title,
            req.task_description,
            serde_json::to_string(&req.task_tags).unwrap_or_else(|_| "[]".to_string()),
            req.command_template,
            req.player_metadata,
        );

        // Acquire semaphore permit before LLM call; released when block exits.
        let llm_text = {
            let _permit = self
                .semaphore
                .acquire()
                .await
                .map_err(|_| AdaptationError::LlmFailed("semaphore_closed".to_string()))?;

            // Recorded call: the service lands one `llm_requests` telemetry
            // row per attempt (real token totals in production; the stubbed
            // test services fall back to the trait's default recording).
            let ctx = arena_core::llm::telemetry::LlmContext {
                session_id: Some(req.session_id),
                task_id: Some(req.task_id),
                ..Default::default()
            };
            let timeout = Duration::from_secs(self.llm_timeout_secs);
            match tokio::time::timeout(
                timeout,
                self.llm.complete_recorded(
                    &self.db,
                    &cfg,
                    "adaptation",
                    ctx.clone(),
                    &system_prompt,
                    &user_prompt,
                ),
            )
            .await
            {
                Ok(res) => res?,
                Err(_) => {
                    // The timed-out future was dropped before it could
                    // record — leave a failed row so the attempt is visible.
                    arena_core::llm::telemetry::record_llm_request(
                        &self.db,
                        arena_core::llm::telemetry::LlmRequestRecord::new("adaptation", &cfg, ctx)
                            .with_duration_ms(timeout.as_millis() as i64)
                            .failed("llm_timeout"),
                    )
                    .await;
                    return Err(AdaptationError::LlmFailed("llm_timeout".to_string()));
                }
            }
        };

        // Parse JSON array; any parse failure triggers a retry at the loop level.
        let tests: Vec<AdaptedTest> = serde_json::from_str(llm_text.trim())
            .map_err(|e| AdaptationError::LlmFailed(format!("parse_error: {e}")))?;

        let original_count = tests.len();
        let tests =
            expand_atomic_tests(tests).map_err(|e| AdaptationError::LlmFailed(e.to_string()))?;
        if tests.len() > original_count {
            self.metrics
                .inc_split_generated_by((tests.len() - original_count) as u64);
        }

        if tests.is_empty() {
            return Err(AdaptationError::LlmFailed("empty_test_list".to_string()));
        }

        let tx = self
            .db
            .begin()
            .await
            .map_err(|e| AdaptationError::DbError(e.to_string()))?;

        for (ordinal, test) in tests.into_iter().enumerate() {
            let command_template = resolve_command_template(&test.command)?;
            // Prefer the LLM-generated answer_template (per-test predicate) over the
            // LLM-generated expected_answer, then fall back to the task-level template
            // forwarded from AdaptationRequest.  This way tasks that define answer_template
            // in TestTemplate (e.g. `result != ""`) automatically apply to all generated rows.
            let row_answer_template = test
                .answer_template
                .filter(|s| !s.trim().is_empty())
                .or_else(|| {
                    (!test.expected_answer.trim().is_empty()).then(|| test.expected_answer.clone())
                })
                .unwrap_or_else(|| req.answer_template.clone());
            entity_tests::ActiveModel {
                id: Set(Uuid::new_v4()),
                command_template: Set(command_template),
                answer_template: Set(row_answer_template),
                fixture_definitions: Set(req.fixture_definitions.clone()),
                created_at: Set(Utc::now()),
                session_id: Set(req.session_id),
                task_id: Set(req.task_id),
                ordinal: Set(ordinal as i32),
                prompt: Set(test.prompt),
                description: Set(None),
                probe_config: Set(None),
                initiator: Set(arena_core::evaluation::INITIATOR_SYSTEM.to_string()),
                registered_by_judge_id: Set(None),
            }
            .insert(&tx)
            .await
            .map_err(|e| AdaptationError::DbError(e.to_string()))?;
        }

        tx.commit()
            .await
            .map_err(|e| AdaptationError::DbError(e.to_string()))?;

        Ok(())
    }
}

// ---------- Helpers ----------

/// Resolve the `command_template` for a newly generated test.
///
/// If `command` is non-empty it is copied into `command_template` so the
/// non-empty invariant holds.  An empty `command` is a hard error.
pub(crate) fn resolve_command_template(command: &str) -> Result<String, AdaptationError> {
    if command.trim().is_empty() {
        Err(AdaptationError::EmptyCommandTemplate)
    } else {
        Ok(command.to_string())
    }
}

/// Build the LLM system prompt, injecting available tool context from
/// `player_metadata` so the model selects appropriate command strategies.
pub(crate) fn build_system_prompt(player_metadata: &serde_json::Value) -> String {
    let base = "You are an AI coding challenge adapter.\n\
Given a test template in Markdown and player metadata, generate concrete test cases.\n\
Output ONLY a valid JSON array of objects. Each object must have these fields:\n\
- \"prompt\": a player-visible description of what the test checks\n\
- \"command\": a fully concrete shell command ready for `sh -c` execution (no placeholders, no markdown fences, no markdown formatting)\n\
- \"expected_answer\": the exact expected stdout after trim; use empty string \"\" when the answer varies or is validated by answer_template\n\
- \"answer_template\" (optional string): a minijinja expression using the variable `result` (the actual trimmed stdout). Provide this field when exact equality is not appropriate. Supported forms: `result != \"\"` (non-empty check), `\"PASS\" in result` (substring present), `\"error\" not in result` (substring absent), `result != \"Failed\"` (not-equal). Omit this field entirely when expected_answer is the exact match.\n\
Each command must validate one concern only. If a source directive checks multiple concerns (for example AGENTS.md and README.md), output separate objects with one command each.\n\
Do not include any explanation, markdown fences, or extra text. Output only the JSON array.";

    let tool_context = build_tool_context(player_metadata);
    format!("{}\n\n{}", base, tool_context)
}

/// Build the tool-aware section of the system prompt from `player_metadata`.
pub(crate) fn build_tool_context(player_metadata: &serde_json::Value) -> String {
    let test_tools: Vec<String> = player_metadata
        .get("test_tools")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default();

    let ai_agents: Vec<String> = player_metadata
        .get("ai_agents")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| {
                    v.get("kind")
                        .or_else(|| v.as_str().map(|_| v))
                        .and_then(|k| k.as_str())
                        .map(str::to_string)
                })
                .collect()
        })
        .unwrap_or_default();

    let tool_line = if test_tools.is_empty() {
        "No test tools declared. Use curl or sh commands only.".to_string()
    } else {
        format!(
            "Available test tools: [{}]. Prefer these tools in commands over curl/sh when appropriate. Only use a tool if it appears in this list.",
            test_tools.join(", ")
        )
    };

    let agent_line = if ai_agents.is_empty() {
        String::new()
    } else {
        format!("\nPlayer agent kinds: [{}].", ai_agents.join(", "))
    };

    format!("{}{}", tool_line, agent_line)
}

impl From<LlmError> for AdaptationError {
    fn from(e: LlmError) -> Self {
        AdaptationError::LlmFailed(e.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adaptation::command_policy::{normalize_shell_command, split_when_safe};

    #[test]
    fn resolve_command_template_copies_non_empty_command() {
        let result = resolve_command_template("echo hello").unwrap();
        assert_eq!(result, "echo hello");
    }

    #[test]
    fn resolve_command_template_errors_on_empty_command() {
        assert!(matches!(
            resolve_command_template(""),
            Err(AdaptationError::EmptyCommandTemplate)
        ));
        assert!(matches!(
            resolve_command_template("   "),
            Err(AdaptationError::EmptyCommandTemplate)
        ));
    }

    #[test]
    fn build_tool_context_with_tools() {
        let meta = serde_json::json!({
            "test_tools": ["agent-browser", "curl"],
            "ai_agents": [{"kind": "opencode"}]
        });
        let ctx = build_tool_context(&meta);
        assert!(ctx.contains("agent-browser"));
        assert!(ctx.contains("curl"));
        assert!(ctx.contains("Prefer these tools"));
        assert!(ctx.contains("opencode"));
    }

    #[test]
    fn build_tool_context_no_tools() {
        let meta = serde_json::json!({});
        let ctx = build_tool_context(&meta);
        assert!(ctx.contains("No test tools declared"));
    }

    #[test]
    fn adapted_test_deserializes() {
        let json = r#"[
            {"prompt": "check echo", "command": "echo hello", "expected_answer": "hello"},
            {"prompt": "check env", "command": "printenv HOME", "expected_answer": "/root"},
            {"prompt": "check non-empty", "command": "curl http://localhost/", "expected_answer": "", "answer_template": "result != \"\""}
        ]"#;
        let tests: Vec<AdaptedTest> = serde_json::from_str(json).unwrap();
        assert_eq!(tests.len(), 3);
        assert_eq!(tests[0].command, "echo hello");
        assert!(tests[0].answer_template.is_none());
        assert_eq!(tests[1].expected_answer, "/root");
        assert_eq!(tests[2].answer_template.as_deref(), Some("result != \"\""));
    }

    #[test]
    fn answer_template_resolution_prefers_llm_over_task_level() {
        // LLM-provided non-empty answer_template wins.
        let llm_tpl = Some("result != \"\"".to_string());
        let task_tpl = "task_level".to_string();
        let resolved = llm_tpl
            .filter(|s| !s.trim().is_empty())
            .unwrap_or_else(|| task_tpl.clone());
        assert_eq!(resolved, "result != \"\"");

        // LLM omits it → task-level used.
        let llm_none: Option<String> = None;
        let resolved2 = llm_none
            .filter(|s| !s.trim().is_empty())
            .unwrap_or_else(|| task_tpl.clone());
        assert_eq!(resolved2, "task_level");

        // LLM sends empty string → task-level used.
        let llm_empty = Some("  ".to_string());
        let resolved3 = llm_empty
            .filter(|s| !s.trim().is_empty())
            .unwrap_or_else(|| task_tpl.clone());
        assert_eq!(resolved3, "task_level");
    }

    #[test]
    fn adapted_test_rejects_missing_field() {
        let json = r#"[{"prompt": "p", "command": "c"}]"#;
        let res: Result<Vec<AdaptedTest>, _> = serde_json::from_str(json);
        assert!(res.is_err(), "expected missing field rejection");
    }

    #[test]
    fn adapted_test_parse_error_on_non_array() {
        let json = r#"{"prompt": "p", "command": "c", "expected_answer": "a"}"#;
        let res: Result<Vec<AdaptedTest>, _> = serde_json::from_str(json);
        assert!(res.is_err(), "expected non-array rejection");
    }

    #[test]
    fn command_normalization_strips_markdown_fences() {
        let command = "```sh\ntest -f ./AGENTS.md\n```";
        let normalized = normalize_shell_command(command).expect("normalized");
        assert_eq!(normalized, "test -f ./AGENTS.md");
    }

    #[test]
    fn split_when_safe_splits_agents_and_readme_checks() {
        let command = "test -f ./AGENTS.md && test -f ./README.md";
        let split = split_when_safe(command).expect("split");
        assert_eq!(split, vec!["test -f ./AGENTS.md", "test -f ./README.md"]);
    }

    #[test]
    fn expansion_rejects_ambiguous_multi_concern_command() {
        let tests = vec![AdaptedTest {
            prompt: "check docs".to_string(),
            command: "cat ./AGENTS.md | grep -q TODO || cat ./README.md | grep -q TODO".to_string(),
            expected_answer: String::new(),
            answer_template: None,
        }];
        let err =
            expand_atomic_tests(tests).expect_err("must reject ambiguous multi-concern command");
        assert!(err.contains("multi_concern_ambiguous"));
    }
}
